/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- API payloads are checked by response status and server validation.
'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useMemo,useState,type ClipboardEvent} from 'react';
import {defaultGradingConfig,gradeTotal,normalizeGradingConfig,type GradeItem,type GradingConfig,type ModelAnswer} from './grading';
import {parseTable} from './table-data';
import {teacherGradingPolicy} from './ai-grading-policy';
type Summary={id:string;student_name:string;classroom:string;round:number;submitted_at:string}; type Answer={result:string;explanation:string;image:string;imageName:string;rows?:{column:string;value:string;reason:string}[]}; type Submission=Summary&{answers:Answer[]}; type StoredGrade={submission_id:string;classroom:string;round:number;items:GradeItem[];total_score:number;source:'manual'|'ai';updated_at:string};
const EVALUATION_ROUND=2;
const SUMMARY_CACHE_KEY=`datapick-teacher-summaries-round-${EVALUATION_ROUND}-v1`;
const formatGradedAt=(value:string)=>{const date=new Date(value);if(Number.isNaN(date.getTime()))return'';return `${date.getMonth()+1}/${date.getDate()} ${date.getHours()}:${String(date.getMinutes()).padStart(2,'0')}`};
function cachedSummaries():Summary[]|null{try{const value=JSON.parse(sessionStorage.getItem(SUMMARY_CACHE_KEY)??'null');return Array.isArray(value)&&value.every(r=>r&&typeof r.id==='string'&&typeof r.student_name==='string'&&typeof r.classroom==='string'&&Number.isInteger(r.round)&&typeof r.submitted_at==='string'&&!Number.isNaN(Date.parse(r.submitted_at)))?value:null}catch{return null}}
function latestSummaries(rows:Summary[]):Summary[]{const latest=new Map<string,Summary>();for(const row of rows){if(row.round!==EVALUATION_ROUND)continue;const key=`${row.round}:${row.classroom}`;const old=latest.get(key);if(!old||row.submitted_at>old.submitted_at||row.submitted_at===old.submitted_at&&row.id>old.id)latest.set(key,row)}return [...latest.values()].sort((a,b)=>a.round-b.round||a.classroom.localeCompare(b.classroom,'en',{numeric:true}))}
const titles=['이상 데이터 찾기','결측 데이터','차트로 표현하고 의미 해석하기','피봇 테이블로 정보 추출하기','데이터 관계 해석']; const blankItems=():GradeItem[]=>defaultGradingConfig.criteria.map(c=>({key:c.key,title:c.title,score:4,comment:''})); const classOf=(n:string)=>/^\d{4}$/.test(n)?n[1]:'unknown'; const groupOf=(r:Summary)=>`${r.round}:${classOf(r.classroom)}`; const groupLabel=(group:string)=>{const [round,cls]=group.split(':');return cls==='unknown'?`${round}회차 학번 확인 필요`:`${round}회차 ${cls}반`};
const modelHelp=['학생과 동일하게 이상 데이터의 열, 값, 판단 이유를 행별로 입력하세요.','결측 행을 제거한 전체 표를 제목 행부터 붙여넣으세요.','모범 차트를 붙여넣고, 차트 선택 이유와 핵심 해석을 작성하세요.','완성된 피봇 테이블을 붙여넣고 구성과 수치 해석을 작성하세요.','관계 분석 차트를 붙여넣고 상관·인과를 구분한 해석을 작성하세요.'];
function ModelAnswerEditor({index,value,onChange}:{index:number;value:ModelAnswer;onChange:(answer:ModelAnswer)=>void}){
 function pasteImage(e:ClipboardEvent<HTMLDivElement>){const file=Array.from(e.clipboardData.items).find(item=>item.type.startsWith('image/'))?.getAsFile();if(!file)return;e.preventDefault();if(file.size>5*1024*1024){alert('이미지는 5MB 이하로 붙여넣어 주세요.');return}const reader=new FileReader();reader.onload=()=>onChange({...value,image:String(reader.result),imageName:file.name||`모범차트-${index+1}.png`});reader.readAsDataURL(file)}
 function updateRow(rowIndex:number,key:'column'|'value'|'reason',text:string){const rows=[...(value.rows??[])];rows[rowIndex]={...rows[rowIndex],[key]:text};onChange({...value,rows})}
 return <section className="model-answer-card"><header><span className="portfolio-number">0{index+1}</span><div><h4>{titles[index]}</h4><p>{modelHelp[index]}</p></div></header>
  {index===0?<div className="model-answer-body"><div className="model-answer-rows"><div className="model-row model-row-head"><b>열 이름</b><b>값</b><b>이상데이터라고 판단한 이유</b><span/></div>{(value.rows??[]).map((row,rowIndex)=><div className="model-row" key={rowIndex}><input value={row.column} aria-label={`모범답안 ${rowIndex+1}행 열 이름`} onChange={e=>updateRow(rowIndex,'column',e.target.value)}/><input value={row.value} aria-label={`모범답안 ${rowIndex+1}행 값`} onChange={e=>updateRow(rowIndex,'value',e.target.value)}/><textarea value={row.reason} aria-label={`모범답안 ${rowIndex+1}행 판단 이유`} onChange={e=>updateRow(rowIndex,'reason',e.target.value)}/><button className="button secondary" onClick={()=>onChange({...value,rows:(value.rows??[]).filter((_,i)=>i!==rowIndex)})}>삭제</button></div>)}</div><button className="button secondary" onClick={()=>onChange({...value,rows:[...(value.rows??[]),{column:'',value:'',reason:''}]})}>+ 행 추가</button></div>:
  <div className="model-answer-body">{index===1||index===3?<><label>모범 결과 표<textarea className="model-table-input" value={value.result} placeholder="스프레드시트에서 제목 행과 전체 데이터를 복사해 붙여넣으세요." onChange={e=>onChange({...value,result:e.target.value})}/></label>{value.result&&<div className="table-wrap"><table><tbody>{parseTable(value.result).slice(0,100).map((row,i)=><tr key={i}>{row.map((cell,j)=>i===0?<th key={j}>{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}</>:<><label>모범 차트 이미지</label><div className={`model-image-paste ${value.image?'has-image':''}`} tabIndex={0} onPaste={pasteImage}>{value.image?<><img src={value.image} alt={`${titles[index]} 모범 차트`}/><button className="button secondary" onClick={()=>onChange({...value,image:'',imageName:''})}>이미지 삭제</button></>:<><b>차트 이미지를 여기에 붙여넣으세요</b><span>영역을 클릭하고 Ctrl+V</span></>}</div></>}{index>=2&&<label>모범 해석과 근거<textarea value={value.explanation} placeholder="학생 답안과 비교할 핵심 해석, 수치와 허용 가능한 표현을 작성하세요." onChange={e=>onChange({...value,explanation:e.target.value})}/></label>}</div>}
 </section>
}
export default function TeacherWorkspace(){
 const [rows,setRows]=useState<Summary[]>([]),[selected,setSelected]=useState<Submission|null>(null),[grades,setGrades]=useState<Record<string,StoredGrade>>({}),[config,setConfig]=useState<GradingConfig>(defaultGradingConfig),[showConfig,setShowConfig]=useState(false),[showAiSetup,setShowAiSetup]=useState(false),[referenceIds,setReferenceIds]=useState<string[]>([]),[targetIds,setTargetIds]=useState<string[]>([]),[classroom,setClassroom]=useState('all'),[collapsedClasses,setCollapsedClasses]=useState<Set<string>>(()=>new Set()),[revision,setRevision]=useState(0),[busy,setBusy]=useState(true),[actionBusy,setActionBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selectedId,setSelectedId]=useState(''),[progress,setProgress]=useState('');
 useEffect(()=>{const c=new AbortController();(async()=>{const cached=cachedSummaries();if(cached){setRows(cached);setBusy(false)}else setBusy(true);setError('');try{const since=cached?.reduce((latest,row)=>row.submitted_at>latest?row.submitted_at:latest,'')||'';const all:Summary[]=[];for(let p=0;;p++){const query=new URLSearchParams({page:String(p)});if(since)query.set('since',since);const r=await fetch(`/api/teacher/submissions?${query}`,{cache:'no-store',signal:c.signal}),d=await r.json();if(!r.ok)throw new Error(d.error);all.push(...d.submissions);if(!d.hasMore)break}if(!c.signal.aborted){const merged=latestSummaries([...(cached??[]),...all]);setRows(merged);try{sessionStorage.setItem(SUMMARY_CACHE_KEY,JSON.stringify(merged))}catch{/* Refresh still works when browser storage is unavailable. */}}const [gr,cr]=await Promise.all([fetch('/api/teacher/grades',{cache:'no-store',signal:c.signal}),fetch('/api/teacher/grading-config',{cache:'no-store',signal:c.signal})]);const gd=await gr.json(),cd=await cr.json();if(!c.signal.aborted){if(gr.ok)setGrades(Object.fromEntries((gd.grades as StoredGrade[]).map(g=>[g.submission_id,g])));if(cr.ok)setConfig(cd.config)}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'불러오지 못했습니다.')}finally{if(!c.signal.aborted)setBusy(false)}})();return()=>c.abort()},[revision]);
 useEffect(()=>{if(!selectedId)return;const c=new AbortController();fetch(`/api/teacher/submissions?id=${selectedId}`,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setSelected(d.submission)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[selectedId,revision]);
 const classes=useMemo(()=>[...new Set(rows.map(groupOf))].sort((a,b)=>Number(a.split(':')[0])-Number(b.split(':')[0])||a.localeCompare(b)),[rows]),visible=rows.filter(r=>classroom==='all'||groupOf(r)===classroom),items=selected?(grades[selected.id]?.items??blankItems()):blankItems();
 function changeModelAnswer(index:number,answer:ModelAnswer){setConfig(current=>{const normalized=normalizeGradingConfig(current);return{...normalized,modelAnswers:normalized.modelAnswers.map((item,i)=>i===index?answer:item)}})}
 async function request(url:string,body:object){const r=await fetch(url,{method:url.includes('grading-config')||url.endsWith('/grades')?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);return d}
 async function saveConfig(){setActionBusy(true);try{await request('/api/teacher/grading-config',{config});setNotice('채점 기준을 저장했습니다.')}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setActionBusy(false)}}
 function changeItem(i:number,p:Partial<GradeItem>){if(!selected)return;setGrades(g=>{const old=g[selected.id],next=(old?.items??blankItems()).map((v,j)=>i===j?{...v,...p}:v);return{...g,[selected.id]:{submission_id:selected.id,classroom:selected.classroom,round:selected.round,items:next,total_score:gradeTotal(next),source:old?.source??'manual',updated_at:old?.updated_at??''}}})}
 function toggleClass(group:string){setCollapsedClasses(current=>{const next=new Set(current);if(next.has(group))next.delete(group);else next.add(group);return next})}
 async function saveGrade(){if(!selected)return;setActionBusy(true);try{const d=await request('/api/teacher/grades',{submissionId:selected.id,classroom:selected.classroom,round:selected.round,items});setGrades(g=>({...g,[selected.id]:d.grade}));setNotice('교사 채점을 저장했습니다.')}catch(e){setError(e instanceof Error?e.message:'저장 실패')}finally{setActionBusy(false)}}
 function openAiSetup(){const scope=/^\d:[0-9]$/.test(classroom)?visible:rows;setReferenceIds(rows.filter(r=>r.round===EVALUATION_ROUND&&grades[r.id]?.source==='manual').map(r=>r.id));setTargetIds(scope.filter(r=>grades[r.id]?.source!=='manual').map(r=>r.id));setError('');setShowAiSetup(true)}
 function toggleId(id:string,setter:typeof setReferenceIds){setter(current=>current.includes(id)?current.filter(v=>v!==id):[...current,id])}
 function toggleTargetClass(group:string){const ids=rows.filter(r=>groupOf(r)===group&&grades[r.id]?.source!=='manual').map(r=>r.id);setTargetIds(current=>ids.every(id=>current.includes(id))?current.filter(id=>!ids.includes(id)):[...new Set([...current,...ids])])}
 async function autoGrade(){const targets=rows.filter(r=>targetIds.includes(r.id));if(!targets.length){setError('AI 채점을 진행할 학생을 선택해 주세요.');return}const calibrationIds=rows.filter(r=>r.round===EVALUATION_ROUND&&referenceIds.includes(r.id)&&grades[r.id]?.source==='manual').map(r=>r.id);if(calibrationIds.length<2){setError('같은 회차에서 참고할 교사 채점 학생을 2명 이상 선택해 주세요. 다른 반도 참고할 수 있습니다.');return}setActionBusy(true);setError('');let done=0;for(const t of targets){setProgress(`${done+1}/${targets.length} ${t.student_name}`);try{const d=await request('/api/teacher/auto-grade',{submissionId:t.id,calibrationIds});setGrades(g=>({...g,[t.id]:d.grade}));done++}catch(e){setError(`${t.student_name}: ${e instanceof Error?e.message:'실패'}`);break}}setProgress('');setActionBusy(false);if(done){setNotice(`${done}명의 AI 채점 초안을 생성했습니다. 검토 후 교사 채점으로 저장해 주세요.`);setShowAiSetup(false)}}
 async function publish(){if(!/^\d:[0-9]$/.test(classroom))return;setActionBusy(true);try{const d=await request('/api/teacher/publish',{classroom:classroom.split(':')[1],round:Number(classroom.split(':')[0]),submissionIds:visible.map(r=>r.id)});setNotice(`${groupLabel(classroom)} ${d.count}명의 점수와 코멘트를 공개했습니다.`)}catch(e){setError(e instanceof Error?e.message:'공개 실패')}finally{setActionBusy(false)}}
 return <main className="teacher-workspace"><div className="section-heading"><div><h2>교사 평가실</h2><p>직접 채점 사례를 만든 뒤 AI 초안을 검토하고 학급에 공개하세요.</p></div><button className="button primary" disabled={busy||actionBusy} onClick={openAiSetup}>AI 채점 시작</button><button className="button secondary" onClick={()=>setShowConfig(v=>!v)}>{showConfig?'기준 닫기':'채점 기준 설정'}</button><button className="button secondary" disabled={busy||actionBusy} onClick={()=>setRevision(v=>v+1)}>새로고침</button></div>{error&&<p className="teacher-alert error" role="alert">{error}</p>}{notice&&<p className="teacher-alert">{notice}</p>}
 {showAiSetup&&<section className="ai-grading-setup" aria-label="AI 채점 설정"><div className="ai-setup-heading"><div><h3>AI 채점 시작</h3><p>교사의 최종 허용 원칙을 우선 적용하고, 저장된 기준·모범답안과 선택한 교사 채점 결과를 함께 참고합니다.</p></div><button className="button secondary" onClick={()=>setShowAiSetup(false)}>닫기</button></div><div className="ai-rule-confirm"><b>적용할 채점 기준</b><span>{config.criteria.map(c=>c.title).join(' · ')}</span><button className="button secondary" onClick={()=>setShowConfig(true)}>기준 확인·수정</button></div><details><summary>실제 AI에 전달할 최종 판정 원칙 확인</summary><p className="answer-text">{teacherGradingPolicy}</p></details><h4>1. 채점에 참고할 교사 직접 채점 학생</h4><p className="ai-help">같은 회차에서 총 2명 이상 선택하세요. 1반의 교사 채점 사례를 다른 반에도 적용할 수 있습니다.</p><div className="ai-selection-groups">{classes.map(c=>{const refs=rows.filter(r=>groupOf(r)===c&&grades[r.id]?.source==='manual');return <fieldset key={c}><legend>{groupLabel(c)}</legend>{refs.length?refs.map(r=><label key={r.id}><input type="checkbox" checked={referenceIds.includes(r.id)} onChange={()=>toggleId(r.id,setReferenceIds)}/><span>{r.classroom} {r.student_name} · {grades[r.id].total_score}점</span></label>):<p>교사가 저장한 채점 결과가 없습니다.</p>}</fieldset>})}</div><h4>2. AI 채점을 진행할 학생</h4><p className="ai-help">학생을 개별 선택하거나 학급 전체를 한 번에 선택할 수 있습니다. 교사 직접 채점 결과는 덮어쓰지 않습니다.</p><div className="ai-selection-groups">{classes.map(c=>{const targets=rows.filter(r=>groupOf(r)===c&&grades[r.id]?.source!=='manual');const all=targets.length>0&&targets.every(r=>targetIds.includes(r.id));return <fieldset key={c}><legend>{groupLabel(c)} <button className="text-button" onClick={()=>toggleTargetClass(c)}>{all?'학급 전체 해제':'학급 전체 선택'}</button></legend>{targets.length?targets.map(r=><label key={r.id}><input type="checkbox" checked={targetIds.includes(r.id)} onChange={()=>toggleId(r.id,setTargetIds)}/><span>{r.classroom} {r.student_name}{grades[r.id]?.source==='ai'?' · AI 초안 있음':' · 채점 전'}</span></label>):<p>선택 가능한 학생이 없습니다.</p>}</fieldset>})}</div><div className="ai-setup-actions"><span>참고 {referenceIds.length}명 · AI 채점 대상 {targetIds.length}명</span><button className="button primary" disabled={actionBusy||!targetIds.length} onClick={autoGrade}>{progress||`${targetIds.length}명 AI 채점 시작`}</button></div></section>}
 {showConfig&&<section className="rubric-editor"><h3>공통 채점 기준</h3><p className="rubric-intro">세부 기준과 학생 제출 형식의 모범답안을 함께 저장합니다.</p><label>공통 안내<textarea value={config.overallInstructions} onChange={e=>setConfig({...config,overallInstructions:e.target.value})}/></label>{config.criteria.map((v,i)=><article key={v.key}><h4>{v.title} · 10/7/4점</h4>{([['세부 항목 1','first'],['세부 항목 2','second'],['상세 판정 기준','guidance'],['추가 허용 답안·감점 예시','exampleAnswer']] as const).map(([label,key])=><label key={key}>{label}<textarea value={v[key]} placeholder={key==='exampleAnswer'?'허용할 다른 표현이나 대표 감점 사유가 있으면 입력하세요.':''} onChange={e=>setConfig({...config,criteria:config.criteria.map((x,j)=>j===i?{...x,[key]:e.target.value}:x)})}/></label>)}</article>)}<div className="model-answer-heading"><h3>영역별 모범답안</h3><p>표의 행·열과 값, 차트 이미지, 해석을 실제 학생 제출물과 같은 형태로 입력하세요.</p></div>{normalizeGradingConfig(config).modelAnswers.map((answer,index)=><ModelAnswerEditor key={index} index={index} value={answer} onChange={next=>changeModelAnswer(index,next)}/>)}<div className="rubric-save"><button className="button primary" disabled={actionBusy} onClick={saveConfig}>채점 기준과 모범답안 저장</button></div></section>}
 <nav className="class-tabs"><button className={classroom==='all'?'active':''} onClick={()=>{setClassroom('all');setSelectedId('');setSelected(null)}}>전체 학급</button>{classes.map(c=><button key={c} className={classroom===c?'active':''} onClick={()=>{setClassroom(c);setSelectedId('');setSelected(null)}}>{groupLabel(c)}</button>)}</nav>{/^\d:[0-9]$/.test(classroom)&&<div className="grading-toolbar"><div><b>{groupLabel(classroom)} 채점</b><span>직접 채점 {Object.values(grades).filter(g=>`${g.round}:${classOf(g.classroom)}`===classroom&&g.source==='manual').length}명 · 초안 {visible.filter(r=>grades[r.id]).length}/{visible.length}명</span></div><button className="button primary" disabled={actionBusy} onClick={openAiSetup}>AI 채점 시작</button><button className="button primary" disabled={actionBusy} onClick={publish}>학급 점수 공개</button></div>}
 {busy?<p>불러오는 중…</p>:classes.filter(c=>classroom==='all'||classroom===c).map(c=>{const collapsed=collapsedClasses.has(c);return <section className={`class-section ${collapsed?'collapsed':''}`} key={c}><button className="class-section-toggle" type="button" aria-expanded={!collapsed} aria-controls={`class-students-${c.replace(':','-')}`} onClick={()=>toggleClass(c)}><h3>{groupLabel(c)}</h3><span className="class-section-count">{rows.filter(r=>groupOf(r)===c).length}명</span><span className="class-section-chevron" aria-hidden="true">⌄</span></button>{!collapsed&&<div className="student-card-grid" id={`class-students-${c.replace(':','-')}`}>{rows.filter(r=>groupOf(r)===c).map(r=>{const grade=grades[r.id],gradedAt=grade?.updated_at?formatGradedAt(grade.updated_at):'';return <button key={r.id} className={`student-answer-card ${selectedId===r.id?'selected':''}`} onClick={()=>setSelectedId(r.id)}><span className="student-card-main"><span className="student-card-identity"><span className="student-card-number">{r.classroom}</span><span className="student-card-name">{r.student_name}</span></span><span className="student-card-score">{grade?`${grade.total_score}점`:'채점 전'}</span></span>{gradedAt&&<span className={`student-card-graded-at ${grade.source}`}><span>{gradedAt}</span><span>{grade.source==='ai'?'AI 채점':'교사 채점'}</span></span>}</button>})}</div>}</section>})}
 {selected&&<section className="portfolio teacher-answer-review"><section className="identity-card review-identity"><div><h2>{selected.student_name} 학생</h2><p>{selected.round}회차 · {selected.classroom} · {grades[selected.id]?.source==='ai'?'AI 초안':grades[selected.id]?'교사 채점':'채점 전'}</p></div><b>{gradeTotal(items)}/30점</b></section>{selected.answers.map((a,i)=><article className="portfolio-card" key={i}><header><span className="portfolio-number">0{i+1}</span><h2>{titles[i]}</h2></header><div className="portfolio-content"><div><span className="preview-label">분석 결과 증거</span>{i===2||i===4?a.image?<a href={a.image} target="_blank" rel="noreferrer"><img className="review-image" src={a.image} alt="제출 차트"/></a>:<p className="empty">차트 없음</p>:a.result?i===0?<div className="table-wrap"><table><tbody>{(a.rows??[]).map((r,j)=><tr key={j}><td>{r.column}</td><td>{r.value}</td><td>{r.reason}</td></tr>)}</tbody></table></div>:<div className="table-wrap"><table><tbody>{parseTable(a.result).map((r,j)=><tr key={j}>{r.map((x,k)=>j?<td key={k}>{x}</td>:<th key={k}>{x}</th>)}</tr>)}</tbody></table></div>:<p className="empty">결과 없음</p>}</div>{i>1&&<div><span className="preview-label">해석과 근거</span><p className="answer-text">{a.explanation||'설명 없음'}</p></div>}</div></article>)}<section className="online-evaluation"><h3>평가요소별 점수와 공개 코멘트</h3><p>7점·4점의 감점 코멘트는 학생에게 공개됩니다. 10점은 비워 두어도 됩니다.</p>{items.map((it,i)=><div className="grade-row" key={it.key}><div><b>{it.title}</b><span>{config.criteria[i].first}<br/>{config.criteria[i].second}</span></div><select value={it.score} onChange={e=>changeItem(i,{score:Number(e.target.value) as 4|7|10})}><option value="10">10점 · 둘 다 충족</option><option value="7">7점 · 하나 충족</option><option value="4">4점 · 모두 미충족</option></select><textarea value={it.comment} onChange={e=>changeItem(i,{comment:e.target.value})} placeholder={it.score===10?'선택 사항 · 특별히 뛰어난 경우 짧은 칭찬':'감점 이유를 짧고 구체적으로 작성하세요.'}/>{it.needsReview&&<em>교사 확인 필요</em>}</div>)}<div className="grade-save"><b>총점 {gradeTotal(items)}/30점</b><button className="button primary" disabled={actionBusy} onClick={saveGrade}>교사 채점 저장</button></div></section></section>}</main>
}
