/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck -- request payloads are validated before persistence.
import { hasTeacherSession } from '../../teacher-session';
import { gradeTotal, validGradeItems } from '../../../grading';
import { json, sameOrigin, supabase } from '../grading-store';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export async function GET(request:Request){if(!hasTeacherSession(request))return json({error:'교사 로그인이 필요합니다.'},401);const db=supabase();if(!db)return json({error:'Supabase 연결 설정이 필요합니다.'},503);const classroom=new URL(request.url).searchParams.get('classroom');const filter=classroom&&/^\d$/.test(classroom)?`&classroom=like._${classroom}__`:'';try{const r=await fetch(`${db.url}/rest/v1/grading_results?select=submission_id,classroom,items,total_score,source,updated_at${filter}`,{headers:db.headers,cache:'no-store'});if(!r.ok)return json({error:'채점 결과 테이블을 확인해 주세요.'},502);return json({grades:await r.json()});}catch{return json({error:'채점 결과를 불러오지 못했습니다.'},502)}}
export async function PUT(request:Request){if(!hasTeacherSession(request))return json({error:'교사 로그인이 필요합니다.'},401);if(!sameOrigin(request))return json({error:'이 웹사이트에서 저장해 주세요.'},403);const db=supabase();if(!db)return json({error:'Supabase 연결 설정이 필요합니다.'},503);try{const b=await request.json();if(!uuid.test(b?.submissionId)||!/^\d{4}$/.test(b?.classroom)||!validGradeItems(b?.items))return json({error:'채점 결과 형식을 확인해 주세요.'},400);const row={submission_id:b.submissionId,classroom:b.classroom,items:b.items,total_score:gradeTotal(b.items),source:'manual',updated_at:new Date().toISOString()};const r=await fetch(`${db.url}/rest/v1/grading_results?on_conflict=submission_id`,{method:'POST',headers:{...db.headers,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)return json({error:'채점 결과를 저장하지 못했습니다.'},502);return json({grade:row});}catch{return json({error:'채점 결과 저장 요청을 확인해 주세요.'},400)}}
